// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy294G2O2JKDVzrTW0s8Ywp1yIHJzJcTM',
    appId: '1:173382576606:web:333c5a4b4053eb9fb7954f',
    messagingSenderId: '173382576606',
    projectId: 'first-d287f',
    authDomain: 'first-d287f.firebaseapp.com',
    storageBucket: 'first-d287f.firebasestorage.app',
    measurementId: 'G-HW5FK1EVZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoon7XkbdKPXRrwjPnVLR5lNnE08hoyYc',
    appId: '1:173382576606:android:c884b12dccaf8993b7954f',
    messagingSenderId: '173382576606',
    projectId: 'first-d287f',
    storageBucket: 'first-d287f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlhhZufqQJvsTXIwIl3efO7583yreYhGI',
    appId: '1:173382576606:ios:762a2eb392a6adf7b7954f',
    messagingSenderId: '173382576606',
    projectId: 'first-d287f',
    storageBucket: 'first-d287f.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlhhZufqQJvsTXIwIl3efO7583yreYhGI',
    appId: '1:173382576606:ios:762a2eb392a6adf7b7954f',
    messagingSenderId: '173382576606',
    projectId: 'first-d287f',
    storageBucket: 'first-d287f.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy294G2O2JKDVzrTW0s8Ywp1yIHJzJcTM',
    appId: '1:173382576606:web:625dbeee13c78e8fb7954f',
    messagingSenderId: '173382576606',
    projectId: 'first-d287f',
    authDomain: 'first-d287f.firebaseapp.com',
    storageBucket: 'first-d287f.firebasestorage.app',
    measurementId: 'G-RFJQ1R7ZH4',
  );
}
